/*
 * Internal module API header file.
 *
 * Generated by SIP 4.19.12
 */

#ifndef _qtpvwidgetsAPI_H
#define _qtpvwidgetsAPI_H

#include <sip.h>

#include <QMetaType>
#include <QThread>

/* These are the qualifiers that are enabled. */
#define SIP_FEATURE_PyQt_MacOSXOnly
#define SIP_FEATURE_PyQt_Process
#define SIP_FEATURE_PyQt_NotBootstrapped
#define SIP_FEATURE_PyQt_Desktop_OpenGL
#define SIP_FEATURE_PyQt_OpenGL
#define SIP_FEATURE_PyQt_RawFont
#define SIP_FEATURE_PyQt_PrintPreviewDialog
#define SIP_FEATURE_PyQt_PrintPreviewWidget
#define SIP_FEATURE_PyQt_Printer
#define SIP_FEATURE_PyQt_PrintDialog
#define SIP_FEATURE_Py_v3
#define SIP_FEATURE_PyQt_qreal_double
#define SIP_FEATURE_PyQt_SSL
#define SIP_FEATURE_PyQt_SessionManager
#define SIP_FEATURE_PyQt_Accessibility
#define SIP_PLATFORM_WS_X11


/*
 * Convenient names to refer to various strings defined in this module.
 * Only the class names are part of the public API.
 */
#define sipNameNr_setConfirmationRequired 0
#define sipName_setConfirmationRequired &sipStrings_qtpvwidgets[0]
#define sipNameNr_mouseDoubleClickEvent 24
#define sipName_mouseDoubleClickEvent &sipStrings_qtpvwidgets[24]
#define sipNameNr_focusPreviousChild 46
#define sipName_focusPreviousChild &sipStrings_qtpvwidgets[46]
#define sipNameNr_focusNextPrevChild 65
#define sipName_focusNextPrevChild &sipStrings_qtpvwidgets[65]
#define sipNameNr_destroySubWindows 84
#define sipName_destroySubWindows &sipStrings_qtpvwidgets[84]
#define sipNameNr_hasHeightForWidth 102
#define sipName_hasHeightForWidth &sipStrings_qtpvwidgets[102]
#define sipNameNr_mouseReleaseEvent 120
#define sipName_mouseReleaseEvent &sipStrings_qtpvwidgets[120]
#define sipNameNr_isSignalConnected 138
#define sipName_isSignalConnected &sipStrings_qtpvwidgets[138]
#define sipNameNr_senderSignalIndex 156
#define sipName_senderSignalIndex &sipStrings_qtpvwidgets[156]
#define sipNameNr_somethingChanged 174
#define sipName_somethingChanged &sipStrings_qtpvwidgets[174]
#define sipNameNr_setIndexFromText 191
#define sipName_setIndexFromText &sipStrings_qtpvwidgets[191]
#define sipNameNr_destroyOldWindow 208
#define sipName_destroyOldWindow &sipStrings_qtpvwidgets[208]
#define sipNameNr_initializeWindow 225
#define sipName_initializeWindow &sipStrings_qtpvwidgets[225]
#define sipNameNr_updateMicroFocus 242
#define sipName_updateMicroFocus &sipStrings_qtpvwidgets[242]
#define sipNameNr_contextMenuEvent 259
#define sipName_contextMenuEvent &sipStrings_qtpvwidgets[259]
#define sipNameNr_inputMethodEvent 276
#define sipName_inputMethodEvent &sipStrings_qtpvwidgets[276]
#define sipNameNr_inputMethodQuery 293
#define sipName_inputMethodQuery &sipStrings_qtpvwidgets[293]
#define sipNameNr_disconnectNotify 310
#define sipName_disconnectNotify &sipStrings_qtpvwidgets[310]
#define sipNameNr_QMDoubleSpinBox 327
#define sipName_QMDoubleSpinBox &sipStrings_qtpvwidgets[327]
#define sipNameNr_initStyleOption 343
#define sipName_initStyleOption &sipStrings_qtpvwidgets[343]
#define sipNameNr_editingFinished 359
#define sipName_editingFinished &sipStrings_qtpvwidgets[359]
#define sipNameNr_minimumSizeHint 375
#define sipName_minimumSizeHint &sipStrings_qtpvwidgets[375]
#define sipNameNr_mousePressEvent 391
#define sipName_mousePressEvent &sipStrings_qtpvwidgets[391]
#define sipNameNr_keyReleaseEvent 407
#define sipName_keyReleaseEvent &sipStrings_qtpvwidgets[407]
#define sipNameNr_deviceTransform 423
#define sipName_deviceTransform &sipStrings_qtpvwidgets[423]
#define sipNameNr_internal_format 439
#define sipName_internal_format &sipStrings_qtpvwidgets[439]
#define sipNameNr_aspectRatioMode 455
#define sipName_aspectRatioMode &sipStrings_qtpvwidgets[455]
#define sipNameNr_focusNextChild 471
#define sipName_focusNextChild &sipStrings_qtpvwidgets[471]
#define sipNameNr_heightForWidth 486
#define sipName_heightForWidth &sipStrings_qtpvwidgets[486]
#define sipNameNr_dragLeaveEvent 501
#define sipName_dragLeaveEvent &sipStrings_qtpvwidgets[501]
#define sipNameNr_dragEnterEvent 516
#define sipName_dragEnterEvent &sipStrings_qtpvwidgets[516]
#define sipNameNr_mouseMoveEvent 531
#define sipName_mouseMoveEvent &sipStrings_qtpvwidgets[531]
#define sipNameNr_QVariantLabel 546
#define sipName_QVariantLabel &sipStrings_qtpvwidgets[546]
#define sipNameNr_changedSignal 560
#define sipName_changedSignal &sipStrings_qtpvwidgets[560]
#define sipNameNr_sharedPainter 574
#define sipName_sharedPainter &sipStrings_qtpvwidgets[574]
#define sipNameNr_destroyWindow 588
#define sipName_destroyWindow &sipStrings_qtpvwidgets[588]
#define sipNameNr_textFromValue 602
#define sipName_textFromValue &sipStrings_qtpvwidgets[602]
#define sipNameNr_valueFromText 616
#define sipName_valueFromText &sipStrings_qtpvwidgets[616]
#define sipNameNr_thresholdTime 630
#define sipName_thresholdTime &sipStrings_qtpvwidgets[630]
#define sipNameNr_dragMoveEvent 644
#define sipName_dragMoveEvent &sipStrings_qtpvwidgets[644]
#define sipNameNr_keyPressEvent 658
#define sipName_keyPressEvent &sipStrings_qtpvwidgets[658]
#define sipNameNr_focusOutEvent 672
#define sipName_focusOutEvent &sipStrings_qtpvwidgets[672]
#define sipNameNr_transformMode 686
#define sipName_transformMode &sipStrings_qtpvwidgets[686]
#define sipNameNr_connectNotify 313
#define sipName_connectNotify &sipStrings_qtpvwidgets[313]
#define sipNameNr_sourceRegion 700
#define sipName_sourceRegion &sipStrings_qtpvwidgets[700]
#define sipNameNr_targetOffset 713
#define sipName_targetOffset &sipStrings_qtpvwidgets[713]
#define sipNameNr_midLineWidth 726
#define sipName_midLineWidth &sipStrings_qtpvwidgets[726]
#define sipNameNr_focusInEvent 739
#define sipName_focusInEvent &sipStrings_qtpvwidgets[739]
#define sipNameNr_boundingRect 752
#define sipName_boundingRect &sipStrings_qtpvwidgets[752]
#define sipNameNr_indexEdited 765
#define sipName_indexEdited &sipStrings_qtpvwidgets[765]
#define sipNameNr_valueEdited 777
#define sipName_valueEdited &sipStrings_qtpvwidgets[777]
#define sipNameNr_initPainter 789
#define sipName_initPainter &sipStrings_qtpvwidgets[789]
#define sipNameNr_nativeEvent 801
#define sipName_nativeEvent &sipStrings_qtpvwidgets[801]
#define sipNameNr_actionEvent 813
#define sipName_actionEvent &sipStrings_qtpvwidgets[813]
#define sipNameNr_stepEnabled 825
#define sipName_stepEnabled &sipStrings_qtpvwidgets[825]
#define sipNameNr_setLineEdit 837
#define sipName_setLineEdit &sipStrings_qtpvwidgets[837]
#define sipNameNr_changeEvent 849
#define sipName_changeEvent &sipStrings_qtpvwidgets[849]
#define sipNameNr_tabletEvent 861
#define sipName_tabletEvent &sipStrings_qtpvwidgets[861]
#define sipNameNr_setDecimals 873
#define sipName_setDecimals &sipStrings_qtpvwidgets[873]
#define sipNameNr_matchPolicy 885
#define sipName_matchPolicy &sipStrings_qtpvwidgets[885]
#define sipNameNr_resizeEvent 897
#define sipName_resizeEvent &sipStrings_qtpvwidgets[897]
#define sipNameNr_paintEngine 909
#define sipName_paintEngine &sipStrings_qtpvwidgets[909]
#define sipNameNr_customEvent 921
#define sipName_customEvent &sipStrings_qtpvwidgets[921]
#define sipNameNr_eventFilter 933
#define sipName_eventFilter &sipStrings_qtpvwidgets[933]
#define sipNameNr_qtpvwidgets 945
#define sipName_qtpvwidgets &sipStrings_qtpvwidgets[945]
#define sipNameNr_setVariant 957
#define sipName_setVariant &sipStrings_qtpvwidgets[957]
#define sipNameNr_QMComboBox 968
#define sipName_QMComboBox &sipStrings_qtpvwidgets[968]
#define sipNameNr_QMLineEdit 979
#define sipName_QMLineEdit &sipStrings_qtpvwidgets[979]
#define sipNameNr_enterEvent 990
#define sipName_enterEvent &sipStrings_qtpvwidgets[990]
#define sipNameNr_leaveEvent 1001
#define sipName_leaveEvent &sipStrings_qtpvwidgets[1001]
#define sipNameNr_cursorRect 1012
#define sipName_cursorRect &sipStrings_qtpvwidgets[1012]
#define sipNameNr_textEdited 1023
#define sipName_textEdited &sipStrings_qtpvwidgets[1023]
#define sipNameNr_constraint 1034
#define sipName_constraint &sipStrings_qtpvwidgets[1034]
#define sipNameNr_closeEvent 1045
#define sipName_closeEvent &sipStrings_qtpvwidgets[1045]
#define sipNameNr_repeatTime 1056
#define sipName_repeatTime &sipStrings_qtpvwidgets[1056]
#define sipNameNr_wheelEvent 1067
#define sipName_wheelEvent &sipStrings_qtpvwidgets[1067]
#define sipNameNr_columnSpan 1078
#define sipName_columnSpan &sipStrings_qtpvwidgets[1078]
#define sipNameNr_paintEvent 1089
#define sipName_paintEvent &sipStrings_qtpvwidgets[1089]
#define sipNameNr_genMipMaps 1100
#define sipName_genMipMaps &sipStrings_qtpvwidgets[1100]
#define sipNameNr_setVisible 1111
#define sipName_setVisible &sipStrings_qtpvwidgets[1111]
#define sipNameNr_childEvent 1122
#define sipName_childEvent &sipStrings_qtpvwidgets[1122]
#define sipNameNr_timerEvent 1133
#define sipName_timerEvent &sipStrings_qtpvwidgets[1133]
#define sipNameNr_QMSpinBox 1144
#define sipName_QMSpinBox &sipStrings_qtpvwidgets[1144]
#define sipNameNr_setSuffix 1154
#define sipName_setSuffix &sipStrings_qtpvwidgets[1154]
#define sipNameNr_setPrefix 1164
#define sipName_setPrefix &sipStrings_qtpvwidgets[1164]
#define sipNameNr_drawFrame 1174
#define sipName_drawFrame &sipStrings_qtpvwidgets[1174]
#define sipNameNr_hidePopup 1184
#define sipName_hidePopup &sipStrings_qtpvwidgets[1184]
#define sipNameNr_showPopup 1194
#define sipName_showPopup &sipStrings_qtpvwidgets[1194]
#define sipNameNr_dropEvent 1204
#define sipName_dropEvent &sipStrings_qtpvwidgets[1204]
#define sipNameNr_hideEvent 1214
#define sipName_hideEvent &sipStrings_qtpvwidgets[1214]
#define sipNameNr_showEvent 1224
#define sipName_showEvent &sipStrings_qtpvwidgets[1224]
#define sipNameNr_moveEvent 1234
#define sipName_moveEvent &sipStrings_qtpvwidgets[1234]
#define sipNameNr_operation 1244
#define sipName_operation &sipStrings_qtpvwidgets[1244]
#define sipNameNr_setFormat 1254
#define sipName_setFormat &sipStrings_qtpvwidgets[1254]
#define sipNameNr_lineWidth 1264
#define sipName_lineWidth &sipStrings_qtpvwidgets[1264]
#define sipNameNr_directory 1274
#define sipName_directory &sipStrings_qtpvwidgets[1274]
#define sipNameNr_alignment 1284
#define sipName_alignment &sipStrings_qtpvwidgets[1284]
#define sipNameNr_receivers 1294
#define sipName_receivers &sipStrings_qtpvwidgets[1294]
#define sipNameNr_precision 1304
#define sipName_precision &sipStrings_qtpvwidgets[1304]
#define sipNameNr_lineEdit 1314
#define sipName_lineEdit &sipStrings_qtpvwidgets[1314]
#define sipNameNr_shortcut 1323
#define sipName_shortcut &sipStrings_qtpvwidgets[1323]
#define sipNameNr_validate 1332
#define sipName_validate &sipStrings_qtpvwidgets[1332]
#define sipNameNr_userData 1341
#define sipName_userData &sipStrings_qtpvwidgets[1341]
#define sipNameNr_sizeHint 1350
#define sipName_sizeHint &sipStrings_qtpvwidgets[1350]
#define sipNameNr_fillRule 1359
#define sipName_fillRule &sipStrings_qtpvwidgets[1359]
#define sipNameNr_tabArray 1368
#define sipName_tabArray &sipStrings_qtpvwidgets[1368]
#define sipNameNr_tabStops 1377
#define sipName_tabStops &sipStrings_qtpvwidgets[1377]
#define sipNameNr_nameType 1386
#define sipName_nameType &sipStrings_qtpvwidgets[1386]
#define sipNameNr_position 1395
#define sipName_position &sipStrings_qtpvwidgets[1395]
#define sipNameNr_setValue 1404
#define sipName_setValue &sipStrings_qtpvwidgets[1404]
#define sipNameNr_property 1413
#define sipName_property &sipStrings_qtpvwidgets[1413]
#define sipNameNr_setBase 1422
#define sipName_setBase &sipStrings_qtpvwidgets[1422]
#define sipNameNr_setPrec 1430
#define sipName_setPrec &sipStrings_qtpvwidgets[1430]
#define sipNameNr_escaped 1438
#define sipName_escaped &sipStrings_qtpvwidgets[1438]
#define sipNameNr_yMargin 1446
#define sipName_yMargin &sipStrings_qtpvwidgets[1446]
#define sipNameNr_xMargin 1454
#define sipName_xMargin &sipStrings_qtpvwidgets[1454]
#define sipNameNr_rowSpan 1462
#define sipName_rowSpan &sipStrings_qtpvwidgets[1462]
#define sipNameNr_exposed 1470
#define sipName_exposed &sipStrings_qtpvwidgets[1470]
#define sipNameNr_buffers 1478
#define sipName_buffers &sipStrings_qtpvwidgets[1478]
#define sipNameNr_sources 1486
#define sipName_sources &sipStrings_qtpvwidgets[1486]
#define sipNameNr_destroy 1494
#define sipName_destroy &sipStrings_qtpvwidgets[1494]
#define sipNameNr_quality 1502
#define sipName_quality &sipStrings_qtpvwidgets[1502]
#define sipNameNr_devType 1510
#define sipName_devType &sipStrings_qtpvwidgets[1510]
#define sipNameNr_setText 1518
#define sipName_setText &sipStrings_qtpvwidgets[1518]
#define sipNameNr_filters 1526
#define sipName_filters &sipStrings_qtpvwidgets[1526]
#define sipNameNr_enabled 1534
#define sipName_enabled &sipStrings_qtpvwidgets[1534]
#define sipNameNr_entered 1542
#define sipName_entered &sipStrings_qtpvwidgets[1542]
#define sipNameNr_options 1550
#define sipName_options &sipStrings_qtpvwidgets[1550]
#define sipNameNr_setMax 1558
#define sipName_setMax &sipStrings_qtpvwidgets[1558]
#define sipNameNr_setMin 1565
#define sipName_setMin &sipStrings_qtpvwidgets[1565]
#define sipNameNr_sunken 1572
#define sipName_sunken &sipStrings_qtpvwidgets[1572]
#define sipNameNr_stepBy 1579
#define sipName_stepBy &sipStrings_qtpvwidgets[1579]
#define sipNameNr_layers 1586
#define sipName_layers &sipStrings_qtpvwidgets[1586]
#define sipNameNr_stride 1593
#define sipName_stride &sipStrings_qtpvwidgets[1593]
#define sipNameNr_metric 1600
#define sipName_metric &sipStrings_qtpvwidgets[1600]
#define sipNameNr_window 1607
#define sipName_window &sipStrings_qtpvwidgets[1607]
#define sipNameNr_create 1614
#define sipName_create &sipStrings_qtpvwidgets[1614]
#define sipNameNr_proper 1621
#define sipName_proper &sipStrings_qtpvwidgets[1621]
#define sipNameNr_sender 1628
#define sipName_sender &sipStrings_qtpvwidgets[1628]
#define sipNameNr_value9 1635
#define sipName_value9 &sipStrings_qtpvwidgets[1635]
#define sipNameNr_value8 1642
#define sipName_value8 &sipStrings_qtpvwidgets[1642]
#define sipNameNr_value7 1649
#define sipName_value7 &sipStrings_qtpvwidgets[1649]
#define sipNameNr_value6 1656
#define sipName_value6 &sipStrings_qtpvwidgets[1656]
#define sipNameNr_value5 1663
#define sipName_value5 &sipStrings_qtpvwidgets[1663]
#define sipNameNr_value4 1670
#define sipName_value4 &sipStrings_qtpvwidgets[1670]
#define sipNameNr_value3 1677
#define sipName_value3 &sipStrings_qtpvwidgets[1677]
#define sipNameNr_value2 1684
#define sipName_value2 &sipStrings_qtpvwidgets[1684]
#define sipNameNr_value1 1691
#define sipName_value1 &sipStrings_qtpvwidgets[1691]
#define sipNameNr_value0 1698
#define sipName_value0 &sipStrings_qtpvwidgets[1698]
#define sipNameNr_system 1705
#define sipName_system &sipStrings_qtpvwidgets[1705]
#define sipNameNr_symbol 1712
#define sipName_symbol &sipStrings_qtpvwidgets[1712]
#define sipNameNr_suffix 1719
#define sipName_suffix &sipStrings_qtpvwidgets[1719]
#define sipNameNr_offset 1726
#define sipName_offset &sipStrings_qtpvwidgets[1726]
#define sipNameNr_prefix 1733
#define sipName_prefix &sipStrings_qtpvwidgets[1733]
#define sipNameNr_filter 1740
#define sipName_filter &sipStrings_qtpvwidgets[1740]
#define sipNameNr_option 1747
#define sipName_option &sipStrings_qtpvwidgets[1747]
#define sipNameNr_locale 1754
#define sipName_locale &sipStrings_qtpvwidgets[1754]
#define sipNameNr_format 448
#define sipName_format &sipStrings_qtpvwidgets[448]
#define sipNameNr_column 1761
#define sipName_column &sipStrings_qtpvwidgets[1761]
#define sipNameNr_object 1768
#define sipName_object &sipStrings_qtpvwidgets[1768]
#define sipNameNr_parent 1775
#define sipName_parent &sipStrings_qtpvwidgets[1775]
#define sipNameNr_fixup 1782
#define sipName_fixup &sipStrings_qtpvwidgets[1782]
#define sipNameNr_brush 1788
#define sipName_brush &sipStrings_qtpvwidgets[1788]
#define sipNameNr_types 1794
#define sipName_types &sipStrings_qtpvwidgets[1794]
#define sipNameNr_clear 1800
#define sipName_clear &sipStrings_qtpvwidgets[1800]
#define sipNameNr_order 1806
#define sipName_order &sipStrings_qtpvwidgets[1806]
#define sipNameNr_roles 1812
#define sipName_roles &sipStrings_qtpvwidgets[1812]
#define sipNameNr_flags 1818
#define sipName_flags &sipStrings_qtpvwidgets[1818]
#define sipNameNr_event 1824
#define sipName_event &sipStrings_qtpvwidgets[1824]
#define sipNameNr_msecs 1830
#define sipName_msecs &sipStrings_qtpvwidgets[1830]
#define sipNameNr_state 1836
#define sipName_state &sipStrings_qtpvwidgets[1836]
#define sipNameNr_mode 1842
#define sipName_mode &sipStrings_qtpvwidgets[1842]
#define sipNameNr_name 1847
#define sipName_name &sipStrings_qtpvwidgets[1847]
#define sipNameNr_base 1852
#define sipName_base &sipStrings_qtpvwidgets[1852]
#define sipNameNr_fill 1857
#define sipName_fill &sipStrings_qtpvwidgets[1857]
#define sipNameNr_from 1862
#define sipName_from &sipStrings_qtpvwidgets[1862]
#define sipNameNr_sort 1867
#define sipName_sort &sipStrings_qtpvwidgets[1867]
#define sipNameNr_pen 1872
#define sipName_pen &sipStrings_qtpvwidgets[1872]
#define sipNameNr_pid 1876
#define sipName_pid &sipStrings_qtpvwidgets[1876]
#define sipNameNr_pos 1880
#define sipName_pos &sipStrings_qtpvwidgets[1880]
#define sipNameNr_sw 1884
#define sipName_sw &sipStrings_qtpvwidgets[1884]
#define sipNameNr_sh 1791
#define sipName_sh &sipStrings_qtpvwidgets[1791]
#define sipNameNr_sy 1887
#define sipName_sy &sipStrings_qtpvwidgets[1887]
#define sipNameNr_sx 1890
#define sipName_sx &sipStrings_qtpvwidgets[1890]
#define sipNameNr_at 452
#define sipName_at &sipStrings_qtpvwidgets[452]

#define sipMalloc                   sipAPI_qtpvwidgets->api_malloc
#define sipFree                     sipAPI_qtpvwidgets->api_free
#define sipBuildResult              sipAPI_qtpvwidgets->api_build_result
#define sipCallMethod               sipAPI_qtpvwidgets->api_call_method
#define sipCallProcedureMethod      sipAPI_qtpvwidgets->api_call_procedure_method
#define sipCallErrorHandler         sipAPI_qtpvwidgets->api_call_error_handler
#define sipParseResultEx            sipAPI_qtpvwidgets->api_parse_result_ex
#define sipParseResult              sipAPI_qtpvwidgets->api_parse_result
#define sipParseArgs                sipAPI_qtpvwidgets->api_parse_args
#define sipParseKwdArgs             sipAPI_qtpvwidgets->api_parse_kwd_args
#define sipParsePair                sipAPI_qtpvwidgets->api_parse_pair
#define sipInstanceDestroyed        sipAPI_qtpvwidgets->api_instance_destroyed
#define sipInstanceDestroyedEx      sipAPI_qtpvwidgets->api_instance_destroyed_ex
#define sipConvertFromSequenceIndex sipAPI_qtpvwidgets->api_convert_from_sequence_index
#define sipConvertFromSliceObject   sipAPI_qtpvwidgets->api_convert_from_slice_object
#define sipConvertFromVoidPtr       sipAPI_qtpvwidgets->api_convert_from_void_ptr
#define sipConvertToVoidPtr         sipAPI_qtpvwidgets->api_convert_to_void_ptr
#define sipAddException             sipAPI_qtpvwidgets->api_add_exception
#define sipNoFunction               sipAPI_qtpvwidgets->api_no_function
#define sipNoMethod                 sipAPI_qtpvwidgets->api_no_method
#define sipAbstractMethod           sipAPI_qtpvwidgets->api_abstract_method
#define sipBadClass                 sipAPI_qtpvwidgets->api_bad_class
#define sipBadCatcherResult         sipAPI_qtpvwidgets->api_bad_catcher_result
#define sipBadCallableArg           sipAPI_qtpvwidgets->api_bad_callable_arg
#define sipBadOperatorArg           sipAPI_qtpvwidgets->api_bad_operator_arg
#define sipTrace                    sipAPI_qtpvwidgets->api_trace
#define sipTransferBack             sipAPI_qtpvwidgets->api_transfer_back
#define sipTransferTo               sipAPI_qtpvwidgets->api_transfer_to
#define sipTransferBreak            sipAPI_qtpvwidgets->api_transfer_break
#define sipSimpleWrapper_Type       sipAPI_qtpvwidgets->api_simplewrapper_type
#define sipWrapper_Type             sipAPI_qtpvwidgets->api_wrapper_type
#define sipWrapperType_Type         sipAPI_qtpvwidgets->api_wrappertype_type
#define sipVoidPtr_Type             sipAPI_qtpvwidgets->api_voidptr_type
#define sipGetPyObject              sipAPI_qtpvwidgets->api_get_pyobject
#define sipGetAddress               sipAPI_qtpvwidgets->api_get_address
#define sipGetMixinAddress          sipAPI_qtpvwidgets->api_get_mixin_address
#define sipGetCppPtr                sipAPI_qtpvwidgets->api_get_cpp_ptr
#define sipGetComplexCppPtr         sipAPI_qtpvwidgets->api_get_complex_cpp_ptr
#define sipIsPyMethod               sipAPI_qtpvwidgets->api_is_py_method
#define sipCallHook                 sipAPI_qtpvwidgets->api_call_hook
#define sipEndThread                sipAPI_qtpvwidgets->api_end_thread
#define sipConnectRx                sipAPI_qtpvwidgets->api_connect_rx
#define sipDisconnectRx             sipAPI_qtpvwidgets->api_disconnect_rx
#define sipRaiseUnknownException    sipAPI_qtpvwidgets->api_raise_unknown_exception
#define sipRaiseTypeException       sipAPI_qtpvwidgets->api_raise_type_exception
#define sipBadLengthForSlice        sipAPI_qtpvwidgets->api_bad_length_for_slice
#define sipAddTypeInstance          sipAPI_qtpvwidgets->api_add_type_instance
#define sipFreeSipslot              sipAPI_qtpvwidgets->api_free_sipslot
#define sipSameSlot                 sipAPI_qtpvwidgets->api_same_slot
#define sipPySlotExtend             sipAPI_qtpvwidgets->api_pyslot_extend
#define sipConvertRx                sipAPI_qtpvwidgets->api_convert_rx
#define sipAddDelayedDtor           sipAPI_qtpvwidgets->api_add_delayed_dtor
#define sipCanConvertToType         sipAPI_qtpvwidgets->api_can_convert_to_type
#define sipConvertToType            sipAPI_qtpvwidgets->api_convert_to_type
#define sipForceConvertToType       sipAPI_qtpvwidgets->api_force_convert_to_type
#define sipCanConvertToEnum         sipAPI_qtpvwidgets->api_can_convert_to_enum
#define sipConvertToEnum            sipAPI_qtpvwidgets->api_convert_to_enum
#define sipConvertToBool            sipAPI_qtpvwidgets->api_convert_to_bool
#define sipReleaseType              sipAPI_qtpvwidgets->api_release_type
#define sipConvertFromType          sipAPI_qtpvwidgets->api_convert_from_type
#define sipConvertFromNewType       sipAPI_qtpvwidgets->api_convert_from_new_type
#define sipConvertFromNewPyType     sipAPI_qtpvwidgets->api_convert_from_new_pytype
#define sipConvertFromEnum          sipAPI_qtpvwidgets->api_convert_from_enum
#define sipGetState                 sipAPI_qtpvwidgets->api_get_state
#define sipExportSymbol             sipAPI_qtpvwidgets->api_export_symbol
#define sipImportSymbol             sipAPI_qtpvwidgets->api_import_symbol
#define sipFindType                 sipAPI_qtpvwidgets->api_find_type
#define sipFindNamedEnum            sipAPI_qtpvwidgets->api_find_named_enum
#define sipBytes_AsChar             sipAPI_qtpvwidgets->api_bytes_as_char
#define sipBytes_AsString           sipAPI_qtpvwidgets->api_bytes_as_string
#define sipString_AsASCIIChar       sipAPI_qtpvwidgets->api_string_as_ascii_char
#define sipString_AsASCIIString     sipAPI_qtpvwidgets->api_string_as_ascii_string
#define sipString_AsLatin1Char      sipAPI_qtpvwidgets->api_string_as_latin1_char
#define sipString_AsLatin1String    sipAPI_qtpvwidgets->api_string_as_latin1_string
#define sipString_AsUTF8Char        sipAPI_qtpvwidgets->api_string_as_utf8_char
#define sipString_AsUTF8String      sipAPI_qtpvwidgets->api_string_as_utf8_string
#define sipUnicode_AsWChar          sipAPI_qtpvwidgets->api_unicode_as_wchar
#define sipUnicode_AsWString        sipAPI_qtpvwidgets->api_unicode_as_wstring
#define sipConvertFromConstVoidPtr  sipAPI_qtpvwidgets->api_convert_from_const_void_ptr
#define sipConvertFromVoidPtrAndSize    sipAPI_qtpvwidgets->api_convert_from_void_ptr_and_size
#define sipConvertFromConstVoidPtrAndSize   sipAPI_qtpvwidgets->api_convert_from_const_void_ptr_and_size
#define sipInvokeSlot               sipAPI_qtpvwidgets->api_invoke_slot
#define sipInvokeSlotEx             sipAPI_qtpvwidgets->api_invoke_slot_ex
#define sipSaveSlot                 sipAPI_qtpvwidgets->api_save_slot
#define sipClearAnySlotReference    sipAPI_qtpvwidgets->api_clear_any_slot_reference
#define sipVisitSlot                sipAPI_qtpvwidgets->api_visit_slot
#define sipWrappedTypeName(wt)      ((wt)->wt_td->td_cname)
#define sipDeprecated               sipAPI_qtpvwidgets->api_deprecated
#define sipGetReference             sipAPI_qtpvwidgets->api_get_reference
#define sipKeepReference            sipAPI_qtpvwidgets->api_keep_reference
#define sipRegisterProxyResolver    sipAPI_qtpvwidgets->api_register_proxy_resolver
#define sipRegisterPyType           sipAPI_qtpvwidgets->api_register_py_type
#define sipTypeFromPyTypeObject     sipAPI_qtpvwidgets->api_type_from_py_type_object
#define sipTypeScope                sipAPI_qtpvwidgets->api_type_scope
#define sipResolveTypedef           sipAPI_qtpvwidgets->api_resolve_typedef
#define sipRegisterAttributeGetter  sipAPI_qtpvwidgets->api_register_attribute_getter
#define sipIsAPIEnabled             sipAPI_qtpvwidgets->api_is_api_enabled
#define sipSetDestroyOnExit         sipAPI_qtpvwidgets->api_set_destroy_on_exit
#define sipEnableAutoconversion     sipAPI_qtpvwidgets->api_enable_autoconversion
#define sipEnableOverflowChecking   sipAPI_qtpvwidgets->api_enable_overflow_checking
#define sipInitMixin                sipAPI_qtpvwidgets->api_init_mixin
#define sipExportModule             sipAPI_qtpvwidgets->api_export_module
#define sipInitModule               sipAPI_qtpvwidgets->api_init_module
#define sipGetInterpreter           sipAPI_qtpvwidgets->api_get_interpreter
#define sipSetNewUserTypeHandler    sipAPI_qtpvwidgets->api_set_new_user_type_handler
#define sipSetTypeUserData          sipAPI_qtpvwidgets->api_set_type_user_data
#define sipGetTypeUserData          sipAPI_qtpvwidgets->api_get_type_user_data
#define sipPyTypeDict               sipAPI_qtpvwidgets->api_py_type_dict
#define sipPyTypeName               sipAPI_qtpvwidgets->api_py_type_name
#define sipGetCFunction             sipAPI_qtpvwidgets->api_get_c_function
#define sipGetMethod                sipAPI_qtpvwidgets->api_get_method
#define sipFromMethod               sipAPI_qtpvwidgets->api_from_method
#define sipGetDate                  sipAPI_qtpvwidgets->api_get_date
#define sipFromDate                 sipAPI_qtpvwidgets->api_from_date
#define sipGetDateTime              sipAPI_qtpvwidgets->api_get_datetime
#define sipFromDateTime             sipAPI_qtpvwidgets->api_from_datetime
#define sipGetTime                  sipAPI_qtpvwidgets->api_get_time
#define sipFromTime                 sipAPI_qtpvwidgets->api_from_time
#define sipIsUserType               sipAPI_qtpvwidgets->api_is_user_type
#define sipGetFrame                 sipAPI_qtpvwidgets->api_get_frame
#define sipCheckPluginForType       sipAPI_qtpvwidgets->api_check_plugin_for_type
#define sipUnicodeNew               sipAPI_qtpvwidgets->api_unicode_new
#define sipUnicodeWrite             sipAPI_qtpvwidgets->api_unicode_write
#define sipUnicodeData              sipAPI_qtpvwidgets->api_unicode_data
#define sipGetBufferInfo            sipAPI_qtpvwidgets->api_get_buffer_info
#define sipReleaseBufferInfo        sipAPI_qtpvwidgets->api_release_buffer_info
#define sipIsOwnedByPython          sipAPI_qtpvwidgets->api_is_owned_by_python
#define sipIsDerivedClass           sipAPI_qtpvwidgets->api_is_derived_class
#define sipGetUserObject            sipAPI_qtpvwidgets->api_get_user_object
#define sipSetUserObject            sipAPI_qtpvwidgets->api_set_user_object
#define sipRegisterEventHandler     sipAPI_qtpvwidgets->api_register_event_handler
#define sipLong_AsChar              sipAPI_qtpvwidgets->api_long_as_char
#define sipLong_AsSignedChar        sipAPI_qtpvwidgets->api_long_as_signed_char
#define sipLong_AsUnsignedChar      sipAPI_qtpvwidgets->api_long_as_unsigned_char
#define sipLong_AsShort             sipAPI_qtpvwidgets->api_long_as_short
#define sipLong_AsUnsignedShort     sipAPI_qtpvwidgets->api_long_as_unsigned_short
#define sipLong_AsInt               sipAPI_qtpvwidgets->api_long_as_int
#define sipLong_AsUnsignedInt       sipAPI_qtpvwidgets->api_long_as_unsigned_int
#define sipLong_AsLong              sipAPI_qtpvwidgets->api_long_as_long
#define sipLong_AsUnsignedLong      sipAPI_qtpvwidgets->api_long_as_unsigned_long
#define sipLong_AsLongLong          sipAPI_qtpvwidgets->api_long_as_long_long
#define sipLong_AsUnsignedLongLong  sipAPI_qtpvwidgets->api_long_as_unsigned_long_long

/* These are deprecated. */
#define sipMapStringToClass         sipAPI_qtpvwidgets->api_map_string_to_class
#define sipMapIntToClass            sipAPI_qtpvwidgets->api_map_int_to_class
#define sipFindClass                sipAPI_qtpvwidgets->api_find_class
#define sipFindMappedType           sipAPI_qtpvwidgets->api_find_mapped_type
#define sipConvertToArray           sipAPI_qtpvwidgets->api_convert_to_array
#define sipConvertToTypedArray      sipAPI_qtpvwidgets->api_convert_to_typed_array
#define sipEnableGC                 sipAPI_qtpvwidgets->api_enable_gc
#define sipPrintObject              sipAPI_qtpvwidgets->api_print_object
#define sipWrapper_Check(w)         PyObject_TypeCheck((w), sipAPI_qtpvwidgets->api_wrapper_type)
#define sipGetWrapper(p, wt)        sipGetPyObject((p), (wt)->wt_td)
#define sipReleaseInstance(p, wt, s)    sipReleaseType((p), (wt)->wt_td, (s))
#define sipReleaseMappedType        sipReleaseType
#define sipCanConvertToInstance(o, wt, f)   sipCanConvertToType((o), (wt)->wt_td, (f))
#define sipCanConvertToMappedType   sipCanConvertToType
#define sipConvertToInstance(o, wt, t, f, s, e)     sipConvertToType((o), (wt)->wt_td, (t), (f), (s), (e))
#define sipConvertToMappedType      sipConvertToType
#define sipForceConvertToInstance(o, wt, t, f, s, e)    sipForceConvertToType((o), (wt)->wt_td, (t), (f), (s), (e))
#define sipForceConvertToMappedType sipForceConvertToType
#define sipConvertFromInstance(p, wt, t)    sipConvertFromType((p), (wt)->wt_td, (t))
#define sipConvertFromMappedType    sipConvertFromType
#define sipConvertFromNamedEnum(v, pt)  sipConvertFromEnum((v), ((sipEnumTypeObject *)(pt))->type)
#define sipConvertFromNewInstance(p, wt, t) sipConvertFromNewType((p), (wt)->wt_td, (t))

/* The strings used by this module. */
extern const char sipStrings_qtpvwidgets[];

#define sipType_QMLineEdit sipExportedTypes_qtpvwidgets[2]
#define sipClass_QMLineEdit sipExportedTypes_qtpvwidgets[2]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_qtpvwidgets_QMLineEdit;

#define sipType_QMDoubleSpinBox sipExportedTypes_qtpvwidgets[1]
#define sipClass_QMDoubleSpinBox sipExportedTypes_qtpvwidgets[1]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_qtpvwidgets_QMDoubleSpinBox;

#define sipType_QMSpinBox sipExportedTypes_qtpvwidgets[3]
#define sipClass_QMSpinBox sipExportedTypes_qtpvwidgets[3]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_qtpvwidgets_QMSpinBox;

#define sipType_QMComboBox sipExportedTypes_qtpvwidgets[0]
#define sipClass_QMComboBox sipExportedTypes_qtpvwidgets[0]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_qtpvwidgets_QMComboBox;

#define sipType_QVariantLabel sipExportedTypes_qtpvwidgets[4]
#define sipClass_QVariantLabel sipExportedTypes_qtpvwidgets[4]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_qtpvwidgets_QVariantLabel;

/* The SIP API, this module's API and the APIs of any imported modules. */
extern const sipAPIDef *sipAPI_qtpvwidgets;
extern sipExportedModuleDef sipModuleAPI_qtpvwidgets;
extern sipTypeDef *sipExportedTypes_qtpvwidgets[];

#define sipType_Qt_InputMethodQuery sipImportedTypes_qtpvwidgets_QtCore[10].it_td
#define sipEnum_Qt_InputMethodQuery sipImportedTypes_qtpvwidgets_QtCore[10].it_td->u.td_py_type

#define sipType_Qt_WindowFlags sipImportedTypes_qtpvwidgets_QtCore[11].it_td
#define sipClass_Qt_WindowFlags sipImportedTypes_qtpvwidgets_QtCore[11].it_td->u.td_wrapper_type

#define sipType_QObject sipImportedTypes_qtpvwidgets_QtCore[4].it_td
#define sipClass_QObject sipImportedTypes_qtpvwidgets_QtCore[4].it_td->u.td_wrapper_type

#define sipType_QByteArray sipImportedTypes_qtpvwidgets_QtCore[0].it_td
#define sipClass_QByteArray sipImportedTypes_qtpvwidgets_QtCore[0].it_td->u.td_wrapper_type

#define sipType_QEvent sipImportedTypes_qtpvwidgets_QtCore[2].it_td
#define sipClass_QEvent sipImportedTypes_qtpvwidgets_QtCore[2].it_td->u.td_wrapper_type

#define sipType_QTimerEvent sipImportedTypes_qtpvwidgets_QtCore[8].it_td
#define sipClass_QTimerEvent sipImportedTypes_qtpvwidgets_QtCore[8].it_td->u.td_wrapper_type

#define sipType_QChildEvent sipImportedTypes_qtpvwidgets_QtCore[1].it_td
#define sipClass_QChildEvent sipImportedTypes_qtpvwidgets_QtCore[1].it_td->u.td_wrapper_type

#define sipType_QMetaMethod sipImportedTypes_qtpvwidgets_QtCore[3].it_td
#define sipClass_QMetaMethod sipImportedTypes_qtpvwidgets_QtCore[3].it_td->u.td_wrapper_type

#define sipType_QRect sipImportedTypes_qtpvwidgets_QtCore[5].it_td
#define sipClass_QRect sipImportedTypes_qtpvwidgets_QtCore[5].it_td->u.td_wrapper_type

#define sipType_QSize sipImportedTypes_qtpvwidgets_QtCore[6].it_td
#define sipClass_QSize sipImportedTypes_qtpvwidgets_QtCore[6].it_td->u.td_wrapper_type

#define sipType_QVariant sipImportedTypes_qtpvwidgets_QtCore[9].it_td
#define sipClass_QVariant sipImportedTypes_qtpvwidgets_QtCore[9].it_td->u.td_wrapper_type

#define sipType_QString sipImportedTypes_qtpvwidgets_QtCore[7].it_td

#define sipType_quintptr sipImportedTypes_qtpvwidgets_QtCore[12].it_td
extern sipImportedTypeDef sipImportedTypes_qtpvwidgets_QtCore[];
extern sipImportedVirtErrorHandlerDef sipImportedVirtErrorHandlers_qtpvwidgets_QtCore[];

#define sipType_QPaintDevice sipImportedTypes_qtpvwidgets_QtGui[13].it_td
#define sipClass_QPaintDevice sipImportedTypes_qtpvwidgets_QtGui[13].it_td->u.td_wrapper_type

#define sipType_QPaintDevice_PaintDeviceMetric sipImportedTypes_qtpvwidgets_QtGui[14].it_td
#define sipEnum_QPaintDevice_PaintDeviceMetric sipImportedTypes_qtpvwidgets_QtGui[14].it_td->u.td_py_type

#define sipType_QMouseEvent sipImportedTypes_qtpvwidgets_QtGui[11].it_td
#define sipClass_QMouseEvent sipImportedTypes_qtpvwidgets_QtGui[11].it_td->u.td_wrapper_type

#define sipType_QWheelEvent sipImportedTypes_qtpvwidgets_QtGui[22].it_td
#define sipClass_QWheelEvent sipImportedTypes_qtpvwidgets_QtGui[22].it_td->u.td_wrapper_type

#define sipType_QTabletEvent sipImportedTypes_qtpvwidgets_QtGui[20].it_td
#define sipClass_QTabletEvent sipImportedTypes_qtpvwidgets_QtGui[20].it_td->u.td_wrapper_type

#define sipType_QKeyEvent sipImportedTypes_qtpvwidgets_QtGui[10].it_td
#define sipClass_QKeyEvent sipImportedTypes_qtpvwidgets_QtGui[10].it_td->u.td_wrapper_type

#define sipType_QFocusEvent sipImportedTypes_qtpvwidgets_QtGui[7].it_td
#define sipClass_QFocusEvent sipImportedTypes_qtpvwidgets_QtGui[7].it_td->u.td_wrapper_type

#define sipType_QPaintEvent sipImportedTypes_qtpvwidgets_QtGui[16].it_td
#define sipClass_QPaintEvent sipImportedTypes_qtpvwidgets_QtGui[16].it_td->u.td_wrapper_type

#define sipType_QMoveEvent sipImportedTypes_qtpvwidgets_QtGui[12].it_td
#define sipClass_QMoveEvent sipImportedTypes_qtpvwidgets_QtGui[12].it_td->u.td_wrapper_type

#define sipType_QResizeEvent sipImportedTypes_qtpvwidgets_QtGui[18].it_td
#define sipClass_QResizeEvent sipImportedTypes_qtpvwidgets_QtGui[18].it_td->u.td_wrapper_type

#define sipType_QCloseEvent sipImportedTypes_qtpvwidgets_QtGui[1].it_td
#define sipClass_QCloseEvent sipImportedTypes_qtpvwidgets_QtGui[1].it_td->u.td_wrapper_type

#define sipType_QShowEvent sipImportedTypes_qtpvwidgets_QtGui[19].it_td
#define sipClass_QShowEvent sipImportedTypes_qtpvwidgets_QtGui[19].it_td->u.td_wrapper_type

#define sipType_QHideEvent sipImportedTypes_qtpvwidgets_QtGui[8].it_td
#define sipClass_QHideEvent sipImportedTypes_qtpvwidgets_QtGui[8].it_td->u.td_wrapper_type

#define sipType_QContextMenuEvent sipImportedTypes_qtpvwidgets_QtGui[2].it_td
#define sipClass_QContextMenuEvent sipImportedTypes_qtpvwidgets_QtGui[2].it_td->u.td_wrapper_type

#define sipType_QInputMethodEvent sipImportedTypes_qtpvwidgets_QtGui[9].it_td
#define sipClass_QInputMethodEvent sipImportedTypes_qtpvwidgets_QtGui[9].it_td->u.td_wrapper_type

#define sipType_QDropEvent sipImportedTypes_qtpvwidgets_QtGui[6].it_td
#define sipClass_QDropEvent sipImportedTypes_qtpvwidgets_QtGui[6].it_td->u.td_wrapper_type

#define sipType_QDragMoveEvent sipImportedTypes_qtpvwidgets_QtGui[5].it_td
#define sipClass_QDragMoveEvent sipImportedTypes_qtpvwidgets_QtGui[5].it_td->u.td_wrapper_type

#define sipType_QDragEnterEvent sipImportedTypes_qtpvwidgets_QtGui[3].it_td
#define sipClass_QDragEnterEvent sipImportedTypes_qtpvwidgets_QtGui[3].it_td->u.td_wrapper_type

#define sipType_QDragLeaveEvent sipImportedTypes_qtpvwidgets_QtGui[4].it_td
#define sipClass_QDragLeaveEvent sipImportedTypes_qtpvwidgets_QtGui[4].it_td->u.td_wrapper_type

#define sipType_QActionEvent sipImportedTypes_qtpvwidgets_QtGui[0].it_td
#define sipClass_QActionEvent sipImportedTypes_qtpvwidgets_QtGui[0].it_td->u.td_wrapper_type

#define sipType_QPainter sipImportedTypes_qtpvwidgets_QtGui[17].it_td
#define sipClass_QPainter sipImportedTypes_qtpvwidgets_QtGui[17].it_td->u.td_wrapper_type

#define sipType_QPaintEngine sipImportedTypes_qtpvwidgets_QtGui[15].it_td
#define sipClass_QPaintEngine sipImportedTypes_qtpvwidgets_QtGui[15].it_td->u.td_wrapper_type

#define sipType_QValidator_State sipImportedTypes_qtpvwidgets_QtGui[21].it_td
#define sipEnum_QValidator_State sipImportedTypes_qtpvwidgets_QtGui[21].it_td->u.td_py_type
extern sipImportedTypeDef sipImportedTypes_qtpvwidgets_QtGui[];

#define sipType_QWidget sipImportedTypes_qtpvwidgets_QtWidgets[11].it_td
#define sipClass_QWidget sipImportedTypes_qtpvwidgets_QtWidgets[11].it_td->u.td_wrapper_type

#define sipType_QFrame sipImportedTypes_qtpvwidgets_QtWidgets[4].it_td
#define sipClass_QFrame sipImportedTypes_qtpvwidgets_QtWidgets[4].it_td->u.td_wrapper_type

#define sipType_QAbstractSpinBox sipImportedTypes_qtpvwidgets_QtWidgets[0].it_td
#define sipClass_QAbstractSpinBox sipImportedTypes_qtpvwidgets_QtWidgets[0].it_td->u.td_wrapper_type

#define sipType_QAbstractSpinBox_StepEnabled sipImportedTypes_qtpvwidgets_QtWidgets[1].it_td
#define sipClass_QAbstractSpinBox_StepEnabled sipImportedTypes_qtpvwidgets_QtWidgets[1].it_td->u.td_wrapper_type

#define sipType_QComboBox sipImportedTypes_qtpvwidgets_QtWidgets[2].it_td
#define sipClass_QComboBox sipImportedTypes_qtpvwidgets_QtWidgets[2].it_td->u.td_wrapper_type

#define sipType_QLabel sipImportedTypes_qtpvwidgets_QtWidgets[5].it_td
#define sipClass_QLabel sipImportedTypes_qtpvwidgets_QtWidgets[5].it_td->u.td_wrapper_type

#define sipType_QLineEdit sipImportedTypes_qtpvwidgets_QtWidgets[6].it_td
#define sipClass_QLineEdit sipImportedTypes_qtpvwidgets_QtWidgets[6].it_td->u.td_wrapper_type

#define sipType_QSpinBox sipImportedTypes_qtpvwidgets_QtWidgets[7].it_td
#define sipClass_QSpinBox sipImportedTypes_qtpvwidgets_QtWidgets[7].it_td->u.td_wrapper_type

#define sipType_QDoubleSpinBox sipImportedTypes_qtpvwidgets_QtWidgets[3].it_td
#define sipClass_QDoubleSpinBox sipImportedTypes_qtpvwidgets_QtWidgets[3].it_td->u.td_wrapper_type

#define sipType_QStyleOptionFrame sipImportedTypes_qtpvwidgets_QtWidgets[9].it_td
#define sipClass_QStyleOptionFrame sipImportedTypes_qtpvwidgets_QtWidgets[9].it_td->u.td_wrapper_type

#define sipType_QStyleOptionSpinBox sipImportedTypes_qtpvwidgets_QtWidgets[10].it_td
#define sipClass_QStyleOptionSpinBox sipImportedTypes_qtpvwidgets_QtWidgets[10].it_td->u.td_wrapper_type

#define sipType_QStyleOptionComboBox sipImportedTypes_qtpvwidgets_QtWidgets[8].it_td
#define sipClass_QStyleOptionComboBox sipImportedTypes_qtpvwidgets_QtWidgets[8].it_td->u.td_wrapper_type
extern sipImportedTypeDef sipImportedTypes_qtpvwidgets_QtWidgets[];

typedef const QMetaObject *(*sip_qt_metaobject_func)(sipSimpleWrapper *,sipTypeDef *);
extern sip_qt_metaobject_func sip_qtpvwidgets_qt_metaobject;

typedef int (*sip_qt_metacall_func)(sipSimpleWrapper *,sipTypeDef *,QMetaObject::Call,int,void **);
extern sip_qt_metacall_func sip_qtpvwidgets_qt_metacall;

typedef bool (*sip_qt_metacast_func)(sipSimpleWrapper *, const sipTypeDef *, const char *, void **);
extern sip_qt_metacast_func sip_qtpvwidgets_qt_metacast;

#endif
