/*
 * Internal module API header file.
 *
 * Generated by SIP 4.19.16
 */

#ifndef _pyqtpvwidgetsAPI_H
#define _pyqtpvwidgetsAPI_H

#include <sip.h>

#include <QMetaType>
#include <QThread>

/* These are the qualifiers that are enabled. */
#define SIP_FEATURE_PyQt_MacOSXOnly
#define SIP_FEATURE_PyQt_Process
#define SIP_FEATURE_PyQt_NotBootstrapped
#define SIP_FEATURE_PyQt_Desktop_OpenGL
#define SIP_FEATURE_PyQt_OpenGL
#define SIP_FEATURE_PyQt_RawFont
#define SIP_FEATURE_PyQt_PrintPreviewDialog
#define SIP_FEATURE_PyQt_PrintPreviewWidget
#define SIP_FEATURE_PyQt_Printer
#define SIP_FEATURE_PyQt_PrintDialog
#define SIP_FEATURE_Py_v3
#define SIP_FEATURE_PyQt_qreal_double
#define SIP_FEATURE_PyQt_SSL
#define SIP_FEATURE_PyQt_SessionManager
#define SIP_FEATURE_PyQt_Accessibility
#define SIP_PLATFORM_WS_X11


/*
 * Convenient names to refer to various strings defined in this module.
 * Only the class names are part of the public API.
 */
#define sipNameNr_setConfirmationRequired 0
#define sipName_setConfirmationRequired &sipStrings_pyqtpvwidgets[0]
#define sipNameNr_mouseDoubleClickEvent 24
#define sipName_mouseDoubleClickEvent &sipStrings_pyqtpvwidgets[24]
#define sipNameNr_focusPreviousChild 46
#define sipName_focusPreviousChild &sipStrings_pyqtpvwidgets[46]
#define sipNameNr_focusNextPrevChild 65
#define sipName_focusNextPrevChild &sipStrings_pyqtpvwidgets[65]
#define sipNameNr_destroySubWindows 84
#define sipName_destroySubWindows &sipStrings_pyqtpvwidgets[84]
#define sipNameNr_hasHeightForWidth 102
#define sipName_hasHeightForWidth &sipStrings_pyqtpvwidgets[102]
#define sipNameNr_mouseReleaseEvent 120
#define sipName_mouseReleaseEvent &sipStrings_pyqtpvwidgets[120]
#define sipNameNr_isSignalConnected 138
#define sipName_isSignalConnected &sipStrings_pyqtpvwidgets[138]
#define sipNameNr_senderSignalIndex 156
#define sipName_senderSignalIndex &sipStrings_pyqtpvwidgets[156]
#define sipNameNr_somethingChanged 174
#define sipName_somethingChanged &sipStrings_pyqtpvwidgets[174]
#define sipNameNr_setIndexFromText 191
#define sipName_setIndexFromText &sipStrings_pyqtpvwidgets[191]
#define sipNameNr_destroyOldWindow 208
#define sipName_destroyOldWindow &sipStrings_pyqtpvwidgets[208]
#define sipNameNr_initializeWindow 225
#define sipName_initializeWindow &sipStrings_pyqtpvwidgets[225]
#define sipNameNr_updateMicroFocus 242
#define sipName_updateMicroFocus &sipStrings_pyqtpvwidgets[242]
#define sipNameNr_contextMenuEvent 259
#define sipName_contextMenuEvent &sipStrings_pyqtpvwidgets[259]
#define sipNameNr_inputMethodEvent 276
#define sipName_inputMethodEvent &sipStrings_pyqtpvwidgets[276]
#define sipNameNr_inputMethodQuery 293
#define sipName_inputMethodQuery &sipStrings_pyqtpvwidgets[293]
#define sipNameNr_disconnectNotify 310
#define sipName_disconnectNotify &sipStrings_pyqtpvwidgets[310]
#define sipNameNr_QMDoubleSpinBox 327
#define sipName_QMDoubleSpinBox &sipStrings_pyqtpvwidgets[327]
#define sipNameNr_initStyleOption 343
#define sipName_initStyleOption &sipStrings_pyqtpvwidgets[343]
#define sipNameNr_editingFinished 359
#define sipName_editingFinished &sipStrings_pyqtpvwidgets[359]
#define sipNameNr_minimumSizeHint 375
#define sipName_minimumSizeHint &sipStrings_pyqtpvwidgets[375]
#define sipNameNr_mousePressEvent 391
#define sipName_mousePressEvent &sipStrings_pyqtpvwidgets[391]
#define sipNameNr_keyReleaseEvent 407
#define sipName_keyReleaseEvent &sipStrings_pyqtpvwidgets[407]
#define sipNameNr_focusNextChild 423
#define sipName_focusNextChild &sipStrings_pyqtpvwidgets[423]
#define sipNameNr_heightForWidth 438
#define sipName_heightForWidth &sipStrings_pyqtpvwidgets[438]
#define sipNameNr_dragLeaveEvent 453
#define sipName_dragLeaveEvent &sipStrings_pyqtpvwidgets[453]
#define sipNameNr_dragEnterEvent 468
#define sipName_dragEnterEvent &sipStrings_pyqtpvwidgets[468]
#define sipNameNr_mouseMoveEvent 483
#define sipName_mouseMoveEvent &sipStrings_pyqtpvwidgets[483]
#define sipNameNr_QVariantLabel 498
#define sipName_QVariantLabel &sipStrings_pyqtpvwidgets[498]
#define sipNameNr_changedSignal 512
#define sipName_changedSignal &sipStrings_pyqtpvwidgets[512]
#define sipNameNr_sharedPainter 526
#define sipName_sharedPainter &sipStrings_pyqtpvwidgets[526]
#define sipNameNr_destroyWindow 540
#define sipName_destroyWindow &sipStrings_pyqtpvwidgets[540]
#define sipNameNr_textFromValue 554
#define sipName_textFromValue &sipStrings_pyqtpvwidgets[554]
#define sipNameNr_valueFromText 568
#define sipName_valueFromText &sipStrings_pyqtpvwidgets[568]
#define sipNameNr_thresholdTime 582
#define sipName_thresholdTime &sipStrings_pyqtpvwidgets[582]
#define sipNameNr_dragMoveEvent 596
#define sipName_dragMoveEvent &sipStrings_pyqtpvwidgets[596]
#define sipNameNr_keyPressEvent 610
#define sipName_keyPressEvent &sipStrings_pyqtpvwidgets[610]
#define sipNameNr_focusOutEvent 624
#define sipName_focusOutEvent &sipStrings_pyqtpvwidgets[624]
#define sipNameNr_connectNotify 313
#define sipName_connectNotify &sipStrings_pyqtpvwidgets[313]
#define sipNameNr_pyqtpvwidgets 638
#define sipName_pyqtpvwidgets &sipStrings_pyqtpvwidgets[638]
#define sipNameNr_focusInEvent 652
#define sipName_focusInEvent &sipStrings_pyqtpvwidgets[652]
#define sipNameNr_indexEdited 665
#define sipName_indexEdited &sipStrings_pyqtpvwidgets[665]
#define sipNameNr_valueEdited 677
#define sipName_valueEdited &sipStrings_pyqtpvwidgets[677]
#define sipNameNr_initPainter 689
#define sipName_initPainter &sipStrings_pyqtpvwidgets[689]
#define sipNameNr_nativeEvent 701
#define sipName_nativeEvent &sipStrings_pyqtpvwidgets[701]
#define sipNameNr_actionEvent 713
#define sipName_actionEvent &sipStrings_pyqtpvwidgets[713]
#define sipNameNr_stepEnabled 725
#define sipName_stepEnabled &sipStrings_pyqtpvwidgets[725]
#define sipNameNr_setLineEdit 737
#define sipName_setLineEdit &sipStrings_pyqtpvwidgets[737]
#define sipNameNr_changeEvent 749
#define sipName_changeEvent &sipStrings_pyqtpvwidgets[749]
#define sipNameNr_tabletEvent 761
#define sipName_tabletEvent &sipStrings_pyqtpvwidgets[761]
#define sipNameNr_setDecimals 773
#define sipName_setDecimals &sipStrings_pyqtpvwidgets[773]
#define sipNameNr_resizeEvent 785
#define sipName_resizeEvent &sipStrings_pyqtpvwidgets[785]
#define sipNameNr_paintEngine 797
#define sipName_paintEngine &sipStrings_pyqtpvwidgets[797]
#define sipNameNr_customEvent 809
#define sipName_customEvent &sipStrings_pyqtpvwidgets[809]
#define sipNameNr_eventFilter 821
#define sipName_eventFilter &sipStrings_pyqtpvwidgets[821]
#define sipNameNr_setVariant 833
#define sipName_setVariant &sipStrings_pyqtpvwidgets[833]
#define sipNameNr_QMComboBox 844
#define sipName_QMComboBox &sipStrings_pyqtpvwidgets[844]
#define sipNameNr_QMLineEdit 855
#define sipName_QMLineEdit &sipStrings_pyqtpvwidgets[855]
#define sipNameNr_enterEvent 866
#define sipName_enterEvent &sipStrings_pyqtpvwidgets[866]
#define sipNameNr_leaveEvent 877
#define sipName_leaveEvent &sipStrings_pyqtpvwidgets[877]
#define sipNameNr_cursorRect 888
#define sipName_cursorRect &sipStrings_pyqtpvwidgets[888]
#define sipNameNr_textEdited 899
#define sipName_textEdited &sipStrings_pyqtpvwidgets[899]
#define sipNameNr_constraint 910
#define sipName_constraint &sipStrings_pyqtpvwidgets[910]
#define sipNameNr_closeEvent 921
#define sipName_closeEvent &sipStrings_pyqtpvwidgets[921]
#define sipNameNr_repeatTime 932
#define sipName_repeatTime &sipStrings_pyqtpvwidgets[932]
#define sipNameNr_wheelEvent 943
#define sipName_wheelEvent &sipStrings_pyqtpvwidgets[943]
#define sipNameNr_columnSpan 954
#define sipName_columnSpan &sipStrings_pyqtpvwidgets[954]
#define sipNameNr_paintEvent 965
#define sipName_paintEvent &sipStrings_pyqtpvwidgets[965]
#define sipNameNr_setVisible 976
#define sipName_setVisible &sipStrings_pyqtpvwidgets[976]
#define sipNameNr_childEvent 987
#define sipName_childEvent &sipStrings_pyqtpvwidgets[987]
#define sipNameNr_timerEvent 998
#define sipName_timerEvent &sipStrings_pyqtpvwidgets[998]
#define sipNameNr_QMSpinBox 1009
#define sipName_QMSpinBox &sipStrings_pyqtpvwidgets[1009]
#define sipNameNr_setSuffix 1019
#define sipName_setSuffix &sipStrings_pyqtpvwidgets[1019]
#define sipNameNr_setPrefix 1029
#define sipName_setPrefix &sipStrings_pyqtpvwidgets[1029]
#define sipNameNr_drawFrame 1039
#define sipName_drawFrame &sipStrings_pyqtpvwidgets[1039]
#define sipNameNr_hidePopup 1049
#define sipName_hidePopup &sipStrings_pyqtpvwidgets[1049]
#define sipNameNr_showPopup 1059
#define sipName_showPopup &sipStrings_pyqtpvwidgets[1059]
#define sipNameNr_dropEvent 1069
#define sipName_dropEvent &sipStrings_pyqtpvwidgets[1069]
#define sipNameNr_hideEvent 1079
#define sipName_hideEvent &sipStrings_pyqtpvwidgets[1079]
#define sipNameNr_showEvent 1089
#define sipName_showEvent &sipStrings_pyqtpvwidgets[1089]
#define sipNameNr_moveEvent 1099
#define sipName_moveEvent &sipStrings_pyqtpvwidgets[1099]
#define sipNameNr_setFormat 1109
#define sipName_setFormat &sipStrings_pyqtpvwidgets[1109]
#define sipNameNr_alignment 1119
#define sipName_alignment &sipStrings_pyqtpvwidgets[1119]
#define sipNameNr_receivers 1129
#define sipName_receivers &sipStrings_pyqtpvwidgets[1129]
#define sipNameNr_lineEdit 1139
#define sipName_lineEdit &sipStrings_pyqtpvwidgets[1139]
#define sipNameNr_validate 1148
#define sipName_validate &sipStrings_pyqtpvwidgets[1148]
#define sipNameNr_sizeHint 1157
#define sipName_sizeHint &sipStrings_pyqtpvwidgets[1157]
#define sipNameNr_setValue 1166
#define sipName_setValue &sipStrings_pyqtpvwidgets[1166]
#define sipNameNr_property 1175
#define sipName_property &sipStrings_pyqtpvwidgets[1175]
#define sipNameNr_setBase 1184
#define sipName_setBase &sipStrings_pyqtpvwidgets[1184]
#define sipNameNr_setPrec 1192
#define sipName_setPrec &sipStrings_pyqtpvwidgets[1192]
#define sipNameNr_escaped 1200
#define sipName_escaped &sipStrings_pyqtpvwidgets[1200]
#define sipNameNr_rowSpan 1208
#define sipName_rowSpan &sipStrings_pyqtpvwidgets[1208]
#define sipNameNr_destroy 1216
#define sipName_destroy &sipStrings_pyqtpvwidgets[1216]
#define sipNameNr_devType 1224
#define sipName_devType &sipStrings_pyqtpvwidgets[1224]
#define sipNameNr_setText 1232
#define sipName_setText &sipStrings_pyqtpvwidgets[1232]
#define sipNameNr_enabled 1240
#define sipName_enabled &sipStrings_pyqtpvwidgets[1240]
#define sipNameNr_entered 1248
#define sipName_entered &sipStrings_pyqtpvwidgets[1248]
#define sipNameNr_setMax 1256
#define sipName_setMax &sipStrings_pyqtpvwidgets[1256]
#define sipNameNr_setMin 1263
#define sipName_setMin &sipStrings_pyqtpvwidgets[1263]
#define sipNameNr_stepBy 1270
#define sipName_stepBy &sipStrings_pyqtpvwidgets[1270]
#define sipNameNr_metric 1277
#define sipName_metric &sipStrings_pyqtpvwidgets[1277]
#define sipNameNr_window 1284
#define sipName_window &sipStrings_pyqtpvwidgets[1284]
#define sipNameNr_create 1291
#define sipName_create &sipStrings_pyqtpvwidgets[1291]
#define sipNameNr_sender 1298
#define sipName_sender &sipStrings_pyqtpvwidgets[1298]
#define sipNameNr_system 1305
#define sipName_system &sipStrings_pyqtpvwidgets[1305]
#define sipNameNr_suffix 1312
#define sipName_suffix &sipStrings_pyqtpvwidgets[1312]
#define sipNameNr_offset 1319
#define sipName_offset &sipStrings_pyqtpvwidgets[1319]
#define sipNameNr_prefix 1326
#define sipName_prefix &sipStrings_pyqtpvwidgets[1326]
#define sipNameNr_format 1333
#define sipName_format &sipStrings_pyqtpvwidgets[1333]
#define sipNameNr_column 1340
#define sipName_column &sipStrings_pyqtpvwidgets[1340]
#define sipNameNr_object 1347
#define sipName_object &sipStrings_pyqtpvwidgets[1347]
#define sipNameNr_fixup 1354
#define sipName_fixup &sipStrings_pyqtpvwidgets[1354]
#define sipNameNr_clear 1360
#define sipName_clear &sipStrings_pyqtpvwidgets[1360]
#define sipNameNr_roles 1366
#define sipName_roles &sipStrings_pyqtpvwidgets[1366]
#define sipNameNr_event 1372
#define sipName_event &sipStrings_pyqtpvwidgets[1372]
#define sipNameNr_mode 1378
#define sipName_mode &sipStrings_pyqtpvwidgets[1378]

#define sipMalloc                   sipAPI_pyqtpvwidgets->api_malloc
#define sipFree                     sipAPI_pyqtpvwidgets->api_free
#define sipBuildResult              sipAPI_pyqtpvwidgets->api_build_result
#define sipCallMethod               sipAPI_pyqtpvwidgets->api_call_method
#define sipCallProcedureMethod      sipAPI_pyqtpvwidgets->api_call_procedure_method
#define sipCallErrorHandler         sipAPI_pyqtpvwidgets->api_call_error_handler
#define sipParseResultEx            sipAPI_pyqtpvwidgets->api_parse_result_ex
#define sipParseResult              sipAPI_pyqtpvwidgets->api_parse_result
#define sipParseArgs                sipAPI_pyqtpvwidgets->api_parse_args
#define sipParseKwdArgs             sipAPI_pyqtpvwidgets->api_parse_kwd_args
#define sipParsePair                sipAPI_pyqtpvwidgets->api_parse_pair
#define sipInstanceDestroyed        sipAPI_pyqtpvwidgets->api_instance_destroyed
#define sipInstanceDestroyedEx      sipAPI_pyqtpvwidgets->api_instance_destroyed_ex
#define sipConvertFromSequenceIndex sipAPI_pyqtpvwidgets->api_convert_from_sequence_index
#define sipConvertFromSliceObject   sipAPI_pyqtpvwidgets->api_convert_from_slice_object
#define sipConvertFromVoidPtr       sipAPI_pyqtpvwidgets->api_convert_from_void_ptr
#define sipConvertToVoidPtr         sipAPI_pyqtpvwidgets->api_convert_to_void_ptr
#define sipAddException             sipAPI_pyqtpvwidgets->api_add_exception
#define sipNoFunction               sipAPI_pyqtpvwidgets->api_no_function
#define sipNoMethod                 sipAPI_pyqtpvwidgets->api_no_method
#define sipAbstractMethod           sipAPI_pyqtpvwidgets->api_abstract_method
#define sipBadClass                 sipAPI_pyqtpvwidgets->api_bad_class
#define sipBadCatcherResult         sipAPI_pyqtpvwidgets->api_bad_catcher_result
#define sipBadCallableArg           sipAPI_pyqtpvwidgets->api_bad_callable_arg
#define sipBadOperatorArg           sipAPI_pyqtpvwidgets->api_bad_operator_arg
#define sipTrace                    sipAPI_pyqtpvwidgets->api_trace
#define sipTransferBack             sipAPI_pyqtpvwidgets->api_transfer_back
#define sipTransferTo               sipAPI_pyqtpvwidgets->api_transfer_to
#define sipTransferBreak            sipAPI_pyqtpvwidgets->api_transfer_break
#define sipSimpleWrapper_Type       sipAPI_pyqtpvwidgets->api_simplewrapper_type
#define sipWrapper_Type             sipAPI_pyqtpvwidgets->api_wrapper_type
#define sipWrapperType_Type         sipAPI_pyqtpvwidgets->api_wrappertype_type
#define sipVoidPtr_Type             sipAPI_pyqtpvwidgets->api_voidptr_type
#define sipGetPyObject              sipAPI_pyqtpvwidgets->api_get_pyobject
#define sipGetAddress               sipAPI_pyqtpvwidgets->api_get_address
#define sipGetMixinAddress          sipAPI_pyqtpvwidgets->api_get_mixin_address
#define sipGetCppPtr                sipAPI_pyqtpvwidgets->api_get_cpp_ptr
#define sipGetComplexCppPtr         sipAPI_pyqtpvwidgets->api_get_complex_cpp_ptr
#define sipIsPyMethod               sipAPI_pyqtpvwidgets->api_is_py_method
#define sipCallHook                 sipAPI_pyqtpvwidgets->api_call_hook
#define sipEndThread                sipAPI_pyqtpvwidgets->api_end_thread
#define sipConnectRx                sipAPI_pyqtpvwidgets->api_connect_rx
#define sipDisconnectRx             sipAPI_pyqtpvwidgets->api_disconnect_rx
#define sipRaiseUnknownException    sipAPI_pyqtpvwidgets->api_raise_unknown_exception
#define sipRaiseTypeException       sipAPI_pyqtpvwidgets->api_raise_type_exception
#define sipBadLengthForSlice        sipAPI_pyqtpvwidgets->api_bad_length_for_slice
#define sipAddTypeInstance          sipAPI_pyqtpvwidgets->api_add_type_instance
#define sipFreeSipslot              sipAPI_pyqtpvwidgets->api_free_sipslot
#define sipSameSlot                 sipAPI_pyqtpvwidgets->api_same_slot
#define sipPySlotExtend             sipAPI_pyqtpvwidgets->api_pyslot_extend
#define sipConvertRx                sipAPI_pyqtpvwidgets->api_convert_rx
#define sipAddDelayedDtor           sipAPI_pyqtpvwidgets->api_add_delayed_dtor
#define sipCanConvertToType         sipAPI_pyqtpvwidgets->api_can_convert_to_type
#define sipConvertToType            sipAPI_pyqtpvwidgets->api_convert_to_type
#define sipForceConvertToType       sipAPI_pyqtpvwidgets->api_force_convert_to_type
#define sipCanConvertToEnum         sipAPI_pyqtpvwidgets->api_can_convert_to_enum
#define sipConvertToEnum            sipAPI_pyqtpvwidgets->api_convert_to_enum
#define sipConvertToBool            sipAPI_pyqtpvwidgets->api_convert_to_bool
#define sipReleaseType              sipAPI_pyqtpvwidgets->api_release_type
#define sipConvertFromType          sipAPI_pyqtpvwidgets->api_convert_from_type
#define sipConvertFromNewType       sipAPI_pyqtpvwidgets->api_convert_from_new_type
#define sipConvertFromNewPyType     sipAPI_pyqtpvwidgets->api_convert_from_new_pytype
#define sipConvertFromEnum          sipAPI_pyqtpvwidgets->api_convert_from_enum
#define sipGetState                 sipAPI_pyqtpvwidgets->api_get_state
#define sipExportSymbol             sipAPI_pyqtpvwidgets->api_export_symbol
#define sipImportSymbol             sipAPI_pyqtpvwidgets->api_import_symbol
#define sipFindType                 sipAPI_pyqtpvwidgets->api_find_type
#define sipFindNamedEnum            sipAPI_pyqtpvwidgets->api_find_named_enum
#define sipBytes_AsChar             sipAPI_pyqtpvwidgets->api_bytes_as_char
#define sipBytes_AsString           sipAPI_pyqtpvwidgets->api_bytes_as_string
#define sipString_AsASCIIChar       sipAPI_pyqtpvwidgets->api_string_as_ascii_char
#define sipString_AsASCIIString     sipAPI_pyqtpvwidgets->api_string_as_ascii_string
#define sipString_AsLatin1Char      sipAPI_pyqtpvwidgets->api_string_as_latin1_char
#define sipString_AsLatin1String    sipAPI_pyqtpvwidgets->api_string_as_latin1_string
#define sipString_AsUTF8Char        sipAPI_pyqtpvwidgets->api_string_as_utf8_char
#define sipString_AsUTF8String      sipAPI_pyqtpvwidgets->api_string_as_utf8_string
#define sipUnicode_AsWChar          sipAPI_pyqtpvwidgets->api_unicode_as_wchar
#define sipUnicode_AsWString        sipAPI_pyqtpvwidgets->api_unicode_as_wstring
#define sipConvertFromConstVoidPtr  sipAPI_pyqtpvwidgets->api_convert_from_const_void_ptr
#define sipConvertFromVoidPtrAndSize    sipAPI_pyqtpvwidgets->api_convert_from_void_ptr_and_size
#define sipConvertFromConstVoidPtrAndSize   sipAPI_pyqtpvwidgets->api_convert_from_const_void_ptr_and_size
#define sipInvokeSlot               sipAPI_pyqtpvwidgets->api_invoke_slot
#define sipInvokeSlotEx             sipAPI_pyqtpvwidgets->api_invoke_slot_ex
#define sipSaveSlot                 sipAPI_pyqtpvwidgets->api_save_slot
#define sipClearAnySlotReference    sipAPI_pyqtpvwidgets->api_clear_any_slot_reference
#define sipVisitSlot                sipAPI_pyqtpvwidgets->api_visit_slot
#define sipWrappedTypeName(wt)      ((wt)->wt_td->td_cname)
#define sipDeprecated               sipAPI_pyqtpvwidgets->api_deprecated
#define sipGetReference             sipAPI_pyqtpvwidgets->api_get_reference
#define sipKeepReference            sipAPI_pyqtpvwidgets->api_keep_reference
#define sipRegisterProxyResolver    sipAPI_pyqtpvwidgets->api_register_proxy_resolver
#define sipRegisterPyType           sipAPI_pyqtpvwidgets->api_register_py_type
#define sipTypeFromPyTypeObject     sipAPI_pyqtpvwidgets->api_type_from_py_type_object
#define sipTypeScope                sipAPI_pyqtpvwidgets->api_type_scope
#define sipResolveTypedef           sipAPI_pyqtpvwidgets->api_resolve_typedef
#define sipRegisterAttributeGetter  sipAPI_pyqtpvwidgets->api_register_attribute_getter
#define sipIsAPIEnabled             sipAPI_pyqtpvwidgets->api_is_api_enabled
#define sipSetDestroyOnExit         sipAPI_pyqtpvwidgets->api_set_destroy_on_exit
#define sipEnableAutoconversion     sipAPI_pyqtpvwidgets->api_enable_autoconversion
#define sipEnableOverflowChecking   sipAPI_pyqtpvwidgets->api_enable_overflow_checking
#define sipInitMixin                sipAPI_pyqtpvwidgets->api_init_mixin
#define sipExportModule             sipAPI_pyqtpvwidgets->api_export_module
#define sipInitModule               sipAPI_pyqtpvwidgets->api_init_module
#define sipGetInterpreter           sipAPI_pyqtpvwidgets->api_get_interpreter
#define sipSetNewUserTypeHandler    sipAPI_pyqtpvwidgets->api_set_new_user_type_handler
#define sipSetTypeUserData          sipAPI_pyqtpvwidgets->api_set_type_user_data
#define sipGetTypeUserData          sipAPI_pyqtpvwidgets->api_get_type_user_data
#define sipPyTypeDict               sipAPI_pyqtpvwidgets->api_py_type_dict
#define sipPyTypeName               sipAPI_pyqtpvwidgets->api_py_type_name
#define sipGetCFunction             sipAPI_pyqtpvwidgets->api_get_c_function
#define sipGetMethod                sipAPI_pyqtpvwidgets->api_get_method
#define sipFromMethod               sipAPI_pyqtpvwidgets->api_from_method
#define sipGetDate                  sipAPI_pyqtpvwidgets->api_get_date
#define sipFromDate                 sipAPI_pyqtpvwidgets->api_from_date
#define sipGetDateTime              sipAPI_pyqtpvwidgets->api_get_datetime
#define sipFromDateTime             sipAPI_pyqtpvwidgets->api_from_datetime
#define sipGetTime                  sipAPI_pyqtpvwidgets->api_get_time
#define sipFromTime                 sipAPI_pyqtpvwidgets->api_from_time
#define sipIsUserType               sipAPI_pyqtpvwidgets->api_is_user_type
#define sipGetFrame                 sipAPI_pyqtpvwidgets->api_get_frame
#define sipCheckPluginForType       sipAPI_pyqtpvwidgets->api_check_plugin_for_type
#define sipUnicodeNew               sipAPI_pyqtpvwidgets->api_unicode_new
#define sipUnicodeWrite             sipAPI_pyqtpvwidgets->api_unicode_write
#define sipUnicodeData              sipAPI_pyqtpvwidgets->api_unicode_data
#define sipGetBufferInfo            sipAPI_pyqtpvwidgets->api_get_buffer_info
#define sipReleaseBufferInfo        sipAPI_pyqtpvwidgets->api_release_buffer_info
#define sipIsOwnedByPython          sipAPI_pyqtpvwidgets->api_is_owned_by_python
#define sipIsDerivedClass           sipAPI_pyqtpvwidgets->api_is_derived_class
#define sipGetUserObject            sipAPI_pyqtpvwidgets->api_get_user_object
#define sipSetUserObject            sipAPI_pyqtpvwidgets->api_set_user_object
#define sipRegisterEventHandler     sipAPI_pyqtpvwidgets->api_register_event_handler
#define sipLong_AsChar              sipAPI_pyqtpvwidgets->api_long_as_char
#define sipLong_AsSignedChar        sipAPI_pyqtpvwidgets->api_long_as_signed_char
#define sipLong_AsUnsignedChar      sipAPI_pyqtpvwidgets->api_long_as_unsigned_char
#define sipLong_AsShort             sipAPI_pyqtpvwidgets->api_long_as_short
#define sipLong_AsUnsignedShort     sipAPI_pyqtpvwidgets->api_long_as_unsigned_short
#define sipLong_AsInt               sipAPI_pyqtpvwidgets->api_long_as_int
#define sipLong_AsUnsignedInt       sipAPI_pyqtpvwidgets->api_long_as_unsigned_int
#define sipLong_AsLong              sipAPI_pyqtpvwidgets->api_long_as_long
#define sipLong_AsUnsignedLong      sipAPI_pyqtpvwidgets->api_long_as_unsigned_long
#define sipLong_AsLongLong          sipAPI_pyqtpvwidgets->api_long_as_long_long
#define sipLong_AsUnsignedLongLong  sipAPI_pyqtpvwidgets->api_long_as_unsigned_long_long
#define sipLong_AsSizeT             sipAPI_pyqtpvwidgets->api_long_as_size_t

/* These are deprecated. */
#define sipMapStringToClass         sipAPI_pyqtpvwidgets->api_map_string_to_class
#define sipMapIntToClass            sipAPI_pyqtpvwidgets->api_map_int_to_class
#define sipFindClass                sipAPI_pyqtpvwidgets->api_find_class
#define sipFindMappedType           sipAPI_pyqtpvwidgets->api_find_mapped_type
#define sipConvertToArray           sipAPI_pyqtpvwidgets->api_convert_to_array
#define sipConvertToTypedArray      sipAPI_pyqtpvwidgets->api_convert_to_typed_array
#define sipEnableGC                 sipAPI_pyqtpvwidgets->api_enable_gc
#define sipPrintObject              sipAPI_pyqtpvwidgets->api_print_object
#define sipWrapper_Check(w)         PyObject_TypeCheck((w), sipAPI_pyqtpvwidgets->api_wrapper_type)
#define sipGetWrapper(p, wt)        sipGetPyObject((p), (wt)->wt_td)
#define sipReleaseInstance(p, wt, s)    sipReleaseType((p), (wt)->wt_td, (s))
#define sipReleaseMappedType        sipReleaseType
#define sipCanConvertToInstance(o, wt, f)   sipCanConvertToType((o), (wt)->wt_td, (f))
#define sipCanConvertToMappedType   sipCanConvertToType
#define sipConvertToInstance(o, wt, t, f, s, e)     sipConvertToType((o), (wt)->wt_td, (t), (f), (s), (e))
#define sipConvertToMappedType      sipConvertToType
#define sipForceConvertToInstance(o, wt, t, f, s, e)    sipForceConvertToType((o), (wt)->wt_td, (t), (f), (s), (e))
#define sipForceConvertToMappedType sipForceConvertToType
#define sipConvertFromInstance(p, wt, t)    sipConvertFromType((p), (wt)->wt_td, (t))
#define sipConvertFromMappedType    sipConvertFromType
#define sipConvertFromNamedEnum(v, pt)  sipConvertFromEnum((v), ((sipEnumTypeObject *)(pt))->type)
#define sipConvertFromNewInstance(p, wt, t) sipConvertFromNewType((p), (wt)->wt_td, (t))

/* The strings used by this module. */
extern const char sipStrings_pyqtpvwidgets[];

#define sipType_QMLineEdit sipExportedTypes_pyqtpvwidgets[2]
#define sipClass_QMLineEdit sipExportedTypes_pyqtpvwidgets[2]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_pyqtpvwidgets_QMLineEdit;

#define sipType_QMDoubleSpinBox sipExportedTypes_pyqtpvwidgets[1]
#define sipClass_QMDoubleSpinBox sipExportedTypes_pyqtpvwidgets[1]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_pyqtpvwidgets_QMDoubleSpinBox;

#define sipType_QMSpinBox sipExportedTypes_pyqtpvwidgets[3]
#define sipClass_QMSpinBox sipExportedTypes_pyqtpvwidgets[3]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_pyqtpvwidgets_QMSpinBox;

#define sipType_QMComboBox sipExportedTypes_pyqtpvwidgets[0]
#define sipClass_QMComboBox sipExportedTypes_pyqtpvwidgets[0]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_pyqtpvwidgets_QMComboBox;

#define sipType_QVariantLabel sipExportedTypes_pyqtpvwidgets[4]
#define sipClass_QVariantLabel sipExportedTypes_pyqtpvwidgets[4]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_pyqtpvwidgets_QVariantLabel;

/* The SIP API, this module's API and the APIs of any imported modules. */
extern const sipAPIDef *sipAPI_pyqtpvwidgets;
extern sipExportedModuleDef sipModuleAPI_pyqtpvwidgets;
extern sipTypeDef *sipExportedTypes_pyqtpvwidgets[];

#define sipType_Qt_InputMethodQuery sipImportedTypes_pyqtpvwidgets_QtCore[10].it_td
#define sipEnum_Qt_InputMethodQuery sipImportedTypes_pyqtpvwidgets_QtCore[10].it_td->u.td_py_type

#define sipType_Qt_WindowFlags sipImportedTypes_pyqtpvwidgets_QtCore[11].it_td
#define sipClass_Qt_WindowFlags sipImportedTypes_pyqtpvwidgets_QtCore[11].it_td->u.td_wrapper_type

#define sipType_QObject sipImportedTypes_pyqtpvwidgets_QtCore[4].it_td
#define sipClass_QObject sipImportedTypes_pyqtpvwidgets_QtCore[4].it_td->u.td_wrapper_type

#define sipType_QByteArray sipImportedTypes_pyqtpvwidgets_QtCore[0].it_td
#define sipClass_QByteArray sipImportedTypes_pyqtpvwidgets_QtCore[0].it_td->u.td_wrapper_type

#define sipType_QEvent sipImportedTypes_pyqtpvwidgets_QtCore[2].it_td
#define sipClass_QEvent sipImportedTypes_pyqtpvwidgets_QtCore[2].it_td->u.td_wrapper_type

#define sipType_QTimerEvent sipImportedTypes_pyqtpvwidgets_QtCore[8].it_td
#define sipClass_QTimerEvent sipImportedTypes_pyqtpvwidgets_QtCore[8].it_td->u.td_wrapper_type

#define sipType_QChildEvent sipImportedTypes_pyqtpvwidgets_QtCore[1].it_td
#define sipClass_QChildEvent sipImportedTypes_pyqtpvwidgets_QtCore[1].it_td->u.td_wrapper_type

#define sipType_QMetaMethod sipImportedTypes_pyqtpvwidgets_QtCore[3].it_td
#define sipClass_QMetaMethod sipImportedTypes_pyqtpvwidgets_QtCore[3].it_td->u.td_wrapper_type

#define sipType_QRect sipImportedTypes_pyqtpvwidgets_QtCore[5].it_td
#define sipClass_QRect sipImportedTypes_pyqtpvwidgets_QtCore[5].it_td->u.td_wrapper_type

#define sipType_QSize sipImportedTypes_pyqtpvwidgets_QtCore[6].it_td
#define sipClass_QSize sipImportedTypes_pyqtpvwidgets_QtCore[6].it_td->u.td_wrapper_type

#define sipType_QVariant sipImportedTypes_pyqtpvwidgets_QtCore[9].it_td
#define sipClass_QVariant sipImportedTypes_pyqtpvwidgets_QtCore[9].it_td->u.td_wrapper_type

#define sipType_QString sipImportedTypes_pyqtpvwidgets_QtCore[7].it_td

#define sipType_quintptr sipImportedTypes_pyqtpvwidgets_QtCore[12].it_td
extern sipImportedTypeDef sipImportedTypes_pyqtpvwidgets_QtCore[];
extern sipImportedVirtErrorHandlerDef sipImportedVirtErrorHandlers_pyqtpvwidgets_QtCore[];

#define sipType_QPaintDevice sipImportedTypes_pyqtpvwidgets_QtGui[13].it_td
#define sipClass_QPaintDevice sipImportedTypes_pyqtpvwidgets_QtGui[13].it_td->u.td_wrapper_type

#define sipType_QPaintDevice_PaintDeviceMetric sipImportedTypes_pyqtpvwidgets_QtGui[14].it_td
#define sipEnum_QPaintDevice_PaintDeviceMetric sipImportedTypes_pyqtpvwidgets_QtGui[14].it_td->u.td_py_type

#define sipType_QMouseEvent sipImportedTypes_pyqtpvwidgets_QtGui[11].it_td
#define sipClass_QMouseEvent sipImportedTypes_pyqtpvwidgets_QtGui[11].it_td->u.td_wrapper_type

#define sipType_QWheelEvent sipImportedTypes_pyqtpvwidgets_QtGui[22].it_td
#define sipClass_QWheelEvent sipImportedTypes_pyqtpvwidgets_QtGui[22].it_td->u.td_wrapper_type

#define sipType_QTabletEvent sipImportedTypes_pyqtpvwidgets_QtGui[20].it_td
#define sipClass_QTabletEvent sipImportedTypes_pyqtpvwidgets_QtGui[20].it_td->u.td_wrapper_type

#define sipType_QKeyEvent sipImportedTypes_pyqtpvwidgets_QtGui[10].it_td
#define sipClass_QKeyEvent sipImportedTypes_pyqtpvwidgets_QtGui[10].it_td->u.td_wrapper_type

#define sipType_QFocusEvent sipImportedTypes_pyqtpvwidgets_QtGui[7].it_td
#define sipClass_QFocusEvent sipImportedTypes_pyqtpvwidgets_QtGui[7].it_td->u.td_wrapper_type

#define sipType_QPaintEvent sipImportedTypes_pyqtpvwidgets_QtGui[16].it_td
#define sipClass_QPaintEvent sipImportedTypes_pyqtpvwidgets_QtGui[16].it_td->u.td_wrapper_type

#define sipType_QMoveEvent sipImportedTypes_pyqtpvwidgets_QtGui[12].it_td
#define sipClass_QMoveEvent sipImportedTypes_pyqtpvwidgets_QtGui[12].it_td->u.td_wrapper_type

#define sipType_QResizeEvent sipImportedTypes_pyqtpvwidgets_QtGui[18].it_td
#define sipClass_QResizeEvent sipImportedTypes_pyqtpvwidgets_QtGui[18].it_td->u.td_wrapper_type

#define sipType_QCloseEvent sipImportedTypes_pyqtpvwidgets_QtGui[1].it_td
#define sipClass_QCloseEvent sipImportedTypes_pyqtpvwidgets_QtGui[1].it_td->u.td_wrapper_type

#define sipType_QShowEvent sipImportedTypes_pyqtpvwidgets_QtGui[19].it_td
#define sipClass_QShowEvent sipImportedTypes_pyqtpvwidgets_QtGui[19].it_td->u.td_wrapper_type

#define sipType_QHideEvent sipImportedTypes_pyqtpvwidgets_QtGui[8].it_td
#define sipClass_QHideEvent sipImportedTypes_pyqtpvwidgets_QtGui[8].it_td->u.td_wrapper_type

#define sipType_QContextMenuEvent sipImportedTypes_pyqtpvwidgets_QtGui[2].it_td
#define sipClass_QContextMenuEvent sipImportedTypes_pyqtpvwidgets_QtGui[2].it_td->u.td_wrapper_type

#define sipType_QInputMethodEvent sipImportedTypes_pyqtpvwidgets_QtGui[9].it_td
#define sipClass_QInputMethodEvent sipImportedTypes_pyqtpvwidgets_QtGui[9].it_td->u.td_wrapper_type

#define sipType_QDropEvent sipImportedTypes_pyqtpvwidgets_QtGui[6].it_td
#define sipClass_QDropEvent sipImportedTypes_pyqtpvwidgets_QtGui[6].it_td->u.td_wrapper_type

#define sipType_QDragMoveEvent sipImportedTypes_pyqtpvwidgets_QtGui[5].it_td
#define sipClass_QDragMoveEvent sipImportedTypes_pyqtpvwidgets_QtGui[5].it_td->u.td_wrapper_type

#define sipType_QDragEnterEvent sipImportedTypes_pyqtpvwidgets_QtGui[3].it_td
#define sipClass_QDragEnterEvent sipImportedTypes_pyqtpvwidgets_QtGui[3].it_td->u.td_wrapper_type

#define sipType_QDragLeaveEvent sipImportedTypes_pyqtpvwidgets_QtGui[4].it_td
#define sipClass_QDragLeaveEvent sipImportedTypes_pyqtpvwidgets_QtGui[4].it_td->u.td_wrapper_type

#define sipType_QActionEvent sipImportedTypes_pyqtpvwidgets_QtGui[0].it_td
#define sipClass_QActionEvent sipImportedTypes_pyqtpvwidgets_QtGui[0].it_td->u.td_wrapper_type

#define sipType_QPainter sipImportedTypes_pyqtpvwidgets_QtGui[17].it_td
#define sipClass_QPainter sipImportedTypes_pyqtpvwidgets_QtGui[17].it_td->u.td_wrapper_type

#define sipType_QPaintEngine sipImportedTypes_pyqtpvwidgets_QtGui[15].it_td
#define sipClass_QPaintEngine sipImportedTypes_pyqtpvwidgets_QtGui[15].it_td->u.td_wrapper_type

#define sipType_QValidator_State sipImportedTypes_pyqtpvwidgets_QtGui[21].it_td
#define sipEnum_QValidator_State sipImportedTypes_pyqtpvwidgets_QtGui[21].it_td->u.td_py_type
extern sipImportedTypeDef sipImportedTypes_pyqtpvwidgets_QtGui[];

#define sipType_QWidget sipImportedTypes_pyqtpvwidgets_QtWidgets[11].it_td
#define sipClass_QWidget sipImportedTypes_pyqtpvwidgets_QtWidgets[11].it_td->u.td_wrapper_type

#define sipType_QFrame sipImportedTypes_pyqtpvwidgets_QtWidgets[4].it_td
#define sipClass_QFrame sipImportedTypes_pyqtpvwidgets_QtWidgets[4].it_td->u.td_wrapper_type

#define sipType_QAbstractSpinBox sipImportedTypes_pyqtpvwidgets_QtWidgets[0].it_td
#define sipClass_QAbstractSpinBox sipImportedTypes_pyqtpvwidgets_QtWidgets[0].it_td->u.td_wrapper_type

#define sipType_QAbstractSpinBox_StepEnabled sipImportedTypes_pyqtpvwidgets_QtWidgets[1].it_td
#define sipClass_QAbstractSpinBox_StepEnabled sipImportedTypes_pyqtpvwidgets_QtWidgets[1].it_td->u.td_wrapper_type

#define sipType_QComboBox sipImportedTypes_pyqtpvwidgets_QtWidgets[2].it_td
#define sipClass_QComboBox sipImportedTypes_pyqtpvwidgets_QtWidgets[2].it_td->u.td_wrapper_type

#define sipType_QLabel sipImportedTypes_pyqtpvwidgets_QtWidgets[5].it_td
#define sipClass_QLabel sipImportedTypes_pyqtpvwidgets_QtWidgets[5].it_td->u.td_wrapper_type

#define sipType_QLineEdit sipImportedTypes_pyqtpvwidgets_QtWidgets[6].it_td
#define sipClass_QLineEdit sipImportedTypes_pyqtpvwidgets_QtWidgets[6].it_td->u.td_wrapper_type

#define sipType_QSpinBox sipImportedTypes_pyqtpvwidgets_QtWidgets[7].it_td
#define sipClass_QSpinBox sipImportedTypes_pyqtpvwidgets_QtWidgets[7].it_td->u.td_wrapper_type

#define sipType_QDoubleSpinBox sipImportedTypes_pyqtpvwidgets_QtWidgets[3].it_td
#define sipClass_QDoubleSpinBox sipImportedTypes_pyqtpvwidgets_QtWidgets[3].it_td->u.td_wrapper_type

#define sipType_QStyleOptionFrame sipImportedTypes_pyqtpvwidgets_QtWidgets[9].it_td
#define sipClass_QStyleOptionFrame sipImportedTypes_pyqtpvwidgets_QtWidgets[9].it_td->u.td_wrapper_type

#define sipType_QStyleOptionSpinBox sipImportedTypes_pyqtpvwidgets_QtWidgets[10].it_td
#define sipClass_QStyleOptionSpinBox sipImportedTypes_pyqtpvwidgets_QtWidgets[10].it_td->u.td_wrapper_type

#define sipType_QStyleOptionComboBox sipImportedTypes_pyqtpvwidgets_QtWidgets[8].it_td
#define sipClass_QStyleOptionComboBox sipImportedTypes_pyqtpvwidgets_QtWidgets[8].it_td->u.td_wrapper_type
extern sipImportedTypeDef sipImportedTypes_pyqtpvwidgets_QtWidgets[];

typedef const QMetaObject *(*sip_qt_metaobject_func)(sipSimpleWrapper *,sipTypeDef *);
extern sip_qt_metaobject_func sip_pyqtpvwidgets_qt_metaobject;

typedef int (*sip_qt_metacall_func)(sipSimpleWrapper *,sipTypeDef *,QMetaObject::Call,int,void **);
extern sip_qt_metacall_func sip_pyqtpvwidgets_qt_metacall;

typedef bool (*sip_qt_metacast_func)(sipSimpleWrapper *, const sipTypeDef *, const char *, void **);
extern sip_qt_metacast_func sip_pyqtpvwidgets_qt_metacast;

#endif
